apiVersion: v2
name: logging-operator
description: The logging-operator manages loki and logging related config.
home: https://github.com/giantswarm/logging-operator
version: 0.40.1
appVersion: 0.40.1
annotations:
  application.giantswarm.io/team: "atlas"
  config.giantswarm.io/version: 1.x.x
